safe:        false
# auto:        true
# server:      true
# server_port: 4000
baseurl:    /
url: http://felquis.com
paginate: 5

source:      ./_source
destination: ./_site
plugins:     ./_source/_plugins

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink: /:year/:title.html